### ISSUE TITLE
Can't customize SMTP port

### ISSUE THREAD

**Issue by anthonator** [swoosh/swoosh#161]
I pretty much have the same use case and issue as #129.

My config and the error I'm seeing are below.

My config:

```elixir
config :identity_context, IdentityContext.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  password: { :system, "SMTP_PASSWORD" },
  port: { :system, "SMTP_PORT" },
  relay: { :system, "SMTP_HOST" },
  username: { :system, "SMTP_USERNAME" }
```

My error:

```
{:error,
 {:retries_exceeded,
  {:network_failure, 'app.mailhog', {:error, :econnrefused}}}}
```

I had a feeling it might be because the port is coming in from the config as a string and `gen_smtp` might not handle this properly. When I switched to a hardcoded integer in my config I got the following error:

```
** (FunctionClauseError) no function clause matching in :gen_smtp_client.to_string/1    
    
    The following arguments were given to :gen_smtp_client.to_string/1:
    
        # 1
        nil
    
    (gen_smtp) /usr/src/app/deps/gen_smtp/src/gen_smtp_client.erl:338: :gen_smtp_client.to_string/1
    (gen_smtp) /usr/src/app/deps/gen_smtp/src/gen_smtp_client.erl:320: :gen_smtp_client.try_AUTH/3
    (gen_smtp) /usr/src/app/deps/gen_smtp/src/gen_smtp_client.erl:204: :gen_smtp_client.do_smtp_session/3
    (gen_smtp) /usr/src/app/deps/gen_smtp/src/gen_smtp_client.erl:143: :gen_smtp_client.try_smtp_sessions/4
    (swoosh) lib/swoosh/adapters/smtp.ex:43: Swoosh.Adapters.SMTP.deliver/2
    (identity_context) lib/identity_context/registration/command.ex:31: IdentityContext.Registration.Command.send_welcome_email/1
```

**Comment by anthonator** [comment]
I'm using Docker as well. That's why my host is `app.mailhog`. This configuration worked with Bamboo.

**Comment by princemaple** [comment]
I'll take a look soon.

**Comment by anthonator** [comment]
I can ping the `app.mailhog` from the Docker instance that's trying to send the emails. So access isn't the issue.

**Comment by princemaple** [comment]
Is it possible to share you docker setup? Mainly the thing you use to send emails. (if it's a common setup, otherwise it's fine I'll try and figure something out)

**Comment by anthonator** [comment]
Here's my `docker-compose.yml`

```yml
version: '2'
services:
  app:
    command: mix run --no-halt
    env_file: .env
    image: sticksnleaves/elixir-project:1.5
    depends_on:
      - app.postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@app.postgres/database
      PORT: 4000
      SMTP_HOST: "app.mailhog"
      SMTP_PORT: 1025
      SMTP_SSL: "false"
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
  app.mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  app.postgres:
    image: postgres:9.6
    volumes:
      - myapp.app.postgres:/var/lib/postgresql/data
volumes:
  myapp.app.postgres:
    driver: local
```
